mariabackup/percona tests: exit if run as root
Running these tests as root is not supported.

diff --git a/systemtests/tests/py2plug-fd-percona-xtrabackup/testrunner b/systemtests/tests/py2plug-fd-percona-xtrabackup/testrunner
--- a/systemtests/tests/py2plug-fd-percona-xtrabackup/testrunner
+++ b/systemtests/tests/py2plug-fd-percona-xtrabackup/testrunner
@@ -10,6 +10,10 @@ set -u
 TestName="$(basename "$(pwd)")"
 export TestName
 
+if [ "$USER" == "root"  ]; then
+ echo "This test cannot be run as user root."
+ exit 1;
+fi
 
 JobName=backup-bareos-fd
 #shellcheck source=../environment.in
