py3plug-fd-percona-xtrabackup passes with mariadb
Backup is recovered and checked

percona test: user current user so that unprivileged users can also run the test

Also reindent the test parameters

Have two different tests for percona and mariadb

two tests

percona test: switch back to master status

Mariadb use own fileset

package mariabackup plugin for deb and rpm

systemtest percona: do recovery test

percona: create startup_mysql_server function

fix mariabackup test

synxc

rename test db variable name for mariabackup

added symlink for py3plug-fd-mariabackup

forgotten debian/bareos-filedaemon-mariabackup-python-plugin.install

added mariabackup

pkglist: updated with bareos-filedaemon-mariabackup-python-plugin

mariadb: use detected MYSQLD

mariadb check: check of MYSQLD is set

mariabackup test: check for mysqld version

mariad: require >= 10.3.0

set variables in parent scope

also limit python3-mariadb

bareos.spec: require mariadb-devel on centos/rhel >=8

FindPrograms: also search in /usr/libexec for mysqld

mariabackup: use --auth-root-authentication-method=socket

mariabackup test: use one version string and allow from 10.0.0 for testing

Revert "bareos.spec: require mariadb-devel on centos/rhel >=8"

This reverts commit 5c914c655cf09cae44e85f36aa77ac5c4c114c27.

mariadb test: use defined variables

percona-test: run with configure mysql binaries

mariadb / percona tests: describe which variables need to be set

do not show variables only for mariadb/mysql scripts

Update MARIADB test variable checks

diff --git a/systemtests/tests/py2plug-fd-percona-xtrabackup/testrunner b/systemtests/tests/py2plug-fd-percona-xtrabackup/testrunner
--- a/systemtests/tests/py2plug-fd-percona-xtrabackup/testrunner
+++ b/systemtests/tests/py2plug-fd-percona-xtrabackup/testrunner
@@ -14,7 +14,7 @@ export TestName
 JobName=backup-bareos-fd
 #shellcheck source=../environment.in
 . ./environment
-MYQL_CLIENT="${MYSQL} --defaults-file=mysqldefaults --user=root"
+MYQL_CLIENT="${MYSQL_CLIENT_BINARY} --defaults-file=mysqldefaults --user=root"
 
 JobName=backup-bareos-fd
 #shellcheck source=../scripts/functions
@@ -22,11 +22,33 @@ JobName=backup-bareos-fd
 "${rscripts}"/cleanup
 "${rscripts}"/setup
 
+
+XTRABACKUP="${XTRABACKUP_BINARY} --defaults-file=mysqldefaults"
+
 shutdown_mysql_server(){
-  [ -f "mysql/data/${HOSTNAME}.pid" ] && kill "$(cat mysql/data/${HOSTNAME}.pid)" || :
+[ -f "mysql/data/${HOSTNAME}.pid" ] && kill "$(cat mysql/data/${HOSTNAME}.pid)" || :
 # kill running mysqld instance listening on our port
 sudo fuser "${test_db_port}"/tcp -k || :
 }
+
+startup_mysql_server(){
+"${MYSQL_DAEMON_BINARY}" --defaults-file=mysqldefaults >mysql/mysql.log 2>&1 &
+
+tries=60
+echo "waiting for mysql server to start"
+while ! $MYQL_CLIENT <<< "select version();"  > /dev/null 2>&1; do
+  [ $((tries-=1)) -eq 0 ] && {
+    echo "Could not start mysql server"
+    cat mysql/mysql.log
+    shutdown_mysql_server
+    exit 1
+  }
+  echo -n "."
+  sleep 1
+done
+
+}
+
 
 
 shutdown_mysql_server
@@ -43,24 +65,11 @@ mkdir -p ${dbHost}
 
 # initialize mysql db
 
-${MYSQLD} --defaults-file=mysqldefaults --initialize-insecure --user="$USER" > mysql/mysql_init.log
-# start mysql server
-${MYSQLD} --defaults-file=mysqldefaults >mysql/mysql.log 2>&1 &
+${MYSQL_DAEMON_BINARY} --defaults-file=mysqldefaults --initialize-insecure --user="$USER" > mysql/mysql_init.log
 
-tries=60
-echo "waiting for mysql server to start"
-while ! $MYQL_CLIENT <<< "select version();"  > /dev/null 2>&1; do
-  [ $((tries-=1)) -eq 0 ] && {
-    echo "Could not start mysql server"
-    cat mysql/mysql.log
-    shutdown_mysql_server
-    exit 1
-  }
-  echo -n "."
-  sleep 1
-done
-
+startup_mysql_server
 xtrabackup_test_db="${db_name}_xtrabackup"
+
 
 start_test
 
@@ -78,10 +87,12 @@ run job=$JobName level=Incremental yes
 wait JobName=$JobName
 status dir
 
-# insert data and run incremental
-insert into test (data) VALUES ('test entry 2')
 
 END_OF_DATA
+
+# insert data and run incremental
+echo "insert into test (data) VALUES ('test entry 2') " | $MYQL_CLIENT "${xtrabackup_test_db}"
+
 run_bareos "$@"
 
 cat <<END_OF_DATA2 >"$tmp/bconcmds"
@@ -115,6 +126,33 @@ if [ -z "$(ls -A "$tmp"/bareos-restores/_percona/)" ]; then
 fi
 
 
+# create new empty data dir
+rm -Rf mysql/data/*
+mkdir -p mysql/data/
+
+TARGETDIR=$(find ./tmp/bareos-restores/_percona/4/ -type d  -name '*001')
+INCDIR1=$(find ./tmp/bareos-restores/_percona/4/ -type d  -name '*002')
+INCDIR2=$(find ./tmp/bareos-restores/_percona/4/ -type d  -name '*002')
+
+${XTRABACKUP} --prepare --target-dir=${TARGETDIR}
+# after prepare a file is left in data dir, this seems to be a bug
+rm -Rf mysql/data/*
+${XTRABACKUP} --copy-back --target-dir=${TARGETDIR}  --incremental-dir=${INCDIR1}  --incremental-dir=${INCDIR2}
+
+
+startup_mysql_server
+
+if ! echo "SELECT * from test " | $MYQL_CLIENT "${xtrabackup_test_db}" | grep "test entry 1"; then
+    echo "test entry 1 not found"
+    estat=2
+fi
+
+if ! echo "SELECT * from test " | $MYQL_CLIENT "${xtrabackup_test_db}" | grep "test entry 2"; then
+    echo "test entry 2 not found"
+    estat=3
+fi
+
+shutdown_mysql_server
 
 check_for_zombie_jobs storage=File
 stop_bareos
